# Generated by Django 6.0.1 on 2026-02-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
